<?php
/**
* ResetView.phtml => Frontend
*
*/

// Check for token
$selector = filter_input(INPUT_GET, 'selector');
$validator = filter_input(INPUT_GET, 'validator');

if ( false !== ctype_xdigit( $selector ) && false !== ctype_xdigit( $validator ) ) :
?>

<div id="login-modal" class="modal-container">
	<form id="login-form" class="modal" action="<?= $requestUrl ?>/user/reset" method="POST">
		<a href="<?= $requestUrl ?>/" class="button-close">&#10005;</a>
		<h3 class="form-title">vcard Password Reset</h3>

		<p>
			You are now able to choose a new password
		</p>

		<input type="hidden" name="selector" value="<?php echo $selector; ?>">
		<input type="hidden" name="validator" value="<?php echo $validator; ?>">

		<label for="new-password">New password</label>
		<input type="password" id="new-password" name="password" placeholder="Enter your new password" required/>

		<input class="button reset-password" type="submit" value="submit">

		<a href="<?= $requestUrl ?>/user/login" class="link-theme">Login to your vcard</a>

	</form>

</div>
<?php endif;?>
