<?php
/**
* SiteView.phtml => Backend
*/
?>

<?php if (!empty($cover[0]['cover_img'])):?>
<div class="vcard-header overlay" style="background: url('<?= $wwwUrl ?>/assets/images/<?= $cover[0]['cover_img']?>') no-repeat center;">
<?php endif;?>

<?php if (empty($cover[0]['cover_img'])):?>
<div class="vcard-header overlay" style="background: url('<?= $wwwUrl ?>/assets/images/default-cover.jpg') no-repeat center;">
<?php endif;?>

	<a class="button-cover js-modal-link" onclick="document.getElementById('js-cover-modal').style.display='block';" href="#">Update cover photo</a>

	<div class="row">

		<!-- vcard photo -->
		<div class="col-sm-4 col-md-4 col-lg-4">
			<div class="container-image">

				<img src="<?= $wwwUrl ?>/assets/images/<?php
				if (!empty($profile[0]['profile_img']) ){
					echo $profile[0]['profile_img'];
				}
				else {
					echo "default-profile.jpg";
				}
				?>" alt="<?php
				if (!empty($sites[0]['first_name'] ) ){
					echo $sites[0]['first_name'];
				}else{
					echo 'shakespeare';
				};?> <?php
				if (!empty($sites[0]['last_name'] ) ){
					echo $sites[0]['last_name'];
				};?>" />

				<a class="button-image js-modal-link" onclick="document.getElementById('js-photo-modal').style.display='block';" href="#">Update photo</a>

			</div>
		</div><!-- col-sm-4 col-md-4 col-lg-4 -->

		<!-- vcard title -->
		<div class="col-sm-8 col-md-8 col-lg-8">
			<div class="title-container">

				<h2><?php
					if (!empty($sites[0]['first_name'] ) ){
						echo $sites[0]['first_name'];
					} else {
						echo 'William';
					};?>
					<?php
					if (!empty($sites[0]['last_name'] ) ){
						echo $sites[0]['last_name'];
					}else {
						echo 'Shakespeare';
					};?></h2>
				<a class="edit-icons js-modal-link" onclick="document.getElementById('js-name-modal').style.display='block';"
				href="#">
				<?php icon('pen');?>
			</a>

		</div>

		<!-- Path to the quotes -->
		<?php
		include( ROOT_PATH . "/application/www/admin/quotes/QuotesView.phtml");
		?>

		<!-- Path to the social media -->
		<?php include( ROOT_PATH . "/application/www/admin/social/SocialView.phtml");?>
	</div>
	<!-- .col-* -->

</div><!-- .vcard-header -->

</div><!-- .row -->

<!-- ============ MODAL PATHS =========== -->

<!-- Modal for the site name -->
<?php include( ROOT_PATH . "/application/www/admin/site/modals/nameModal.phtml");?>

<!-- Modal for the profile photo -->
<?php include( ROOT_PATH . "/application/www/admin/site/modals/profileModal.phtml");?>

<!-- Modal for the cover photo -->
<?php include( ROOT_PATH . "/application/www/admin/site/modals/coverModal.phtml");?>
