<?php
/**
* AboutView.phtml => Backend
*/
?>

<form  id="js-form-about" class="form-about" action="<?= $requestUrl ?>/admin/about/" method="POST">
	<div class="row">
		<div class="col-xs-12 col-sm-6">
			<div class="col-inner">

				<div class="content-title">
					<h3>About <span>Me</span></h3>
				</div>

				<div class="content-body">
					<label for="excerpt">Excerpt</label>
					<textarea id="excerpt" placeholder="Shakespeare was born and raised in Stratford-upon-Avon, Warwickshire. At the age of 18, he married Anne Hathaway, with whom he had three children: Susanna and twins Hamnet and Judith." name="content_short" rows="4" cols="80"><?php

					// Check if the table is not empty
					if (!empty($abouts[0]['content_short']) ) {
						echo $abouts[0]['content_short'];
					};

					?></textarea>

					<label for="readmore">Read More</label>
					<textarea id="readmore" placeholder="Sometime between 1585 and 1592, he began a successful career in London as an actor, writer, and part-owner of a playing company called the Lord Chamberlain's Men, later known as the King's Men." name="content_long" rows="4" cols="80"><?php

					if (!empty($abouts[0]['content_long']) ) {
						echo $abouts[0]['content_long'];
					};

					?></textarea>

				</div><!-- .content-body -->

				<label for="portfolio_url">Portfolio Url</label>
				<input type="text" id="portfolio_url" placeholder="https://en.wikipedia.org/wiki/William_Shakespeare" name="portfolio_url" value="<?php

				if (!empty($abouts[0]['portfolio_url']) ) {
					echo $abouts[0]['portfolio_url'];
				};

				?>" />
			</div>
		</div><!-- .col-xs-12 col-sm-6 -->


		<div class="col-xs-12 col-sm-6">
			<div class="col-inner">

				<div class="content-title">
					<h3 style="opacity: 0;">About <span>Me</span></h3>
				</div>

				<div class="content-body">
					<ul class="info-list">
						<li>
							<label for="residence">Residence</label>
							<input type="text" placeholder="Stratford" name="residence" value="<?php

							if (!empty($abouts[0]['residence']) ) {
								echo $abouts[0]['residence'];
							};

							?>" />
						</li>
						<li>
							<label for="email-input">Email</label>
							<input type="text" id="email-input" placeholder="william@shakespeare.com" name="email" value="<?php

							if (!empty($abouts[0]['email']) ) {
								echo $abouts[0]['email'];
							};

							?>" />
						</li>
						<li>
							<label for="job-title">Job Title</label>
							<input type="text" id="job_type" placeholder="Playwright"name="job_type" value="<?php

							if (!empty($abouts[0]['job_type']) ) {
								echo $abouts[0]['job_type'];
							};

							?>" />
						</li>
						<li>
							<label id="job-availability-label" for="job-availability">Are you available for work?</label>
							<div class="radio-container">
								<input type="radio" id="job-availability-0"   name="job_availability" value="1">
								<label for="job-availability-0">Yes</label>

								<input type="radio" id="job-availability-1" name="job_availability" value="0" <?php

								if ( empty($abouts[0]['job_availability'])) {
									echo 'checked';
								};

								?>>
								<label for="job-availability-1">No</label>
							</div>
						</li>
					</ul>
					<input class="button" type="submit" value="save about me">
				</div>
			</div>
		</div><!-- .col-xs-12 col-sm-6 -->

	</div><!-- .row -->
</form>
