<?php
/**
* QuotesView.phtml => Backend
*/
$quotePlaceholder1 = "The Bard of Avon";
$quotePlaceholder2 = "An Upstart Crow";
$quotePlaceholder3 = "The Immortal Bard";
?>

<div id="quotes-input">

	<?php foreach ($quotes as $quote): ?>
		<span class="quotes">
			<?php
			if (!empty($quotes)) {
				echo $quote['quote_content'];
			};?>
		</span>
	<?php endforeach; ?>

	<?php if (empty($quotes)):?>
		<span class="quotes"><?= $quotePlaceholder1; ?></span>
		<span class="quotes"><?= $quotePlaceholder2; ?></span>
		<span class="quotes"><?= $quotePlaceholder3; ?></span>
	<?php endif;?>

</div>

<div>
	<span id="quotesDisplay">
		<?php
		if (!empty($quotes)) {
			echo $quotes[0]['quote_content'];
		}else {
			echo $quotePlaceholder1;
		}
		?>
	</span>
	<a class="edit-icons js-modal-link" onclick="document.getElementById('js-quotes-modal').style.display='block';"
	href="#">
	<?php icon('pen');?>
</a>
</div>

<div id="js-quotes-modal" class="modal-container">
	<form  id="quotes-form" class="modal fade-in" action="<?= $requestUrl ?>/admin/quotes/" method="POST">
		<span class="button-close" onclick="document.getElementById('js-quotes-modal').style.display='none';">&#10005;</span>
		<h3 class="form-title">Choose Your quotes<span class="form-subtitle">Fill maximum 3</span></h3>

		<div class="social-flex">
			<input type="text" name="quote_content[]" value="<?php
			if (!empty($quotes)) {
				echo $quotes[0]['quote_content'];
			}
			?>"/>
		</div>

		<div class="social-flex">
			<input type="text" name="quote_content[]" value="<?php
			if (!empty($quotes) && (count($quotes) > 1)) {
				echo $quotes[1]['quote_content'];
			}
			?>"/>
		</div>

		<div class="social-flex">
			<input type="text" name="quote_content[]" value="<?php
			if (!empty($quotes) && (count($quotes) > 2)) {
				echo $quotes[2]['quote_content'];
			}
			?>"/>
		</div>

		<input class="button button-primary" type="submit" value="save">

	</form>
</div>
